# Generated by Django 6.0.5 on 2026-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_doctoravailability_and_profile_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['doctor', 'day', 'start_time'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
    ]
